import { Predio, Conta, Fornecedor, Fracao, Aviso, Movimento, Reuniao, Documento, Ocorrencia, GestorCarteira, EmpresaGestoraConfig, ProcessoJuridico, ProcessoProva } from "./types";

export const cpLookup: Record<string, string> = {
  "2840-124": "Seixal",
  "2775-245": "Parede",
  "1000-001": "Lisboa",
  "4000-001": "Porto",
  "8000-001": "Faro",
  "2780-001": "Oeiras",
  "2845-351": "Amora"
};

export const initialPredios: Predio[] = [
  {
    id_predio: "predio-1",
    nome: "Edifício Estrela da Barra",
    morada_linha1: "Rua Bento Rodrigues",
    morada_linha2: "Apt 2B",
    num_porta: "2",
    letra_porta: "A",
    codigo_postal: "2840-124",
    localidade: "Seixal",
    nif: "900123456",
    iban: "PT50 0035 0123 4567 8901 2344 5",
    email: "edificio.estrela@condomanager.pt",
    autoresponder_ativo: true,
    patrimonio: {
      tem_elevador: true,
      num_elevadores: 2,
      tem_garagem: true,
      tem_piscina: false,
      tem_sala_comum: true,
      tem_arrecadacoes_comuns: true,
      tem_jardins: true,
      tem_churrasqueira: false,
      tem_terraco: false,
      tem_ginasio: false,
      tem_spa: false
    }
  }
];

export const initialContas: Conta[] = [
  {
    id_conta: "cta-1",
    id_predio: "predio-1",
    banco: "Caixa Geral de Depósitos",
    iban: "PT50 0035 0123 4567 8901 2344 5",
    tipo: "Ordem (Gestão Corrente)",
    saldo: 4850.25,
    balcao: "Amora Centro",
    morada_balcao: "Avenida da República, 14, Amora",
    contacto_banco: "219 013 112",
    gestor_contas: "Dr. António Fontes"
  },
  {
    id_conta: "cta-2",
    id_predio: "predio-1",
    banco: "CGD Poupança Condomínio",
    iban: "PT50 0035 0123 4567 8901 9999 1",
    tipo: "Fundo Comum de Reserva (FCR)",
    saldo: 12350.75,
    balcao: "Amora Centro",
    morada_balcao: "Avenida da República, 14, Amora",
    contacto_banco: "219 013 112",
    gestor_contas: "Dr. António Fontes"
  }
];

export const initialFornecedores: Fornecedor[] = [
  {
    id_fornecedor: "forn-1",
    id_predio: "predio-1",
    nome: "EDP Comercial",
    nif: "500697340",
    iban: "PT50 0033 0000 1234 5678 9012 3",
    categoria: "Eletricidade Escadas/Elevadores",
    morada: "Avenida 24 de Julho, 12, Lisboa",
    contacto: "808 535 353",
    pessoa_contacto: "Departamento de Clientes Empresariais",
    email_contacto: "edp.comercial@edp.pt",
    data_nascimento: "1980-05-14",
    perfis_pwa: ["TECNICO"],
    pwa_acesso_enviado: true,
    pwa_password_provisoria: "EdpPwa2026!"
  },
  {
    id_fornecedor: "forn-2",
    id_predio: "predio-1",
    nome: "OTIS Elevadores",
    nif: "500112233",
    iban: "PT50 0003 4444 5555 6666 7777 8",
    categoria: "Manutenção Elevadores",
    morada: "Praceta de Algés, 4, Oeiras",
    contacto: "214 156 000",
    pessoa_contacto: "Eng. Rui Barreiro",
    email_contacto: "rui.barreiro@otis.pt",
    telemovel_direto: "912 345 678",
    data_nascimento: "1985-08-13", // Today!
    perfis_pwa: ["TECNICO"],
    pwa_acesso_enviado: true,
    pwa_password_provisoria: "OtisPwa2026!"
  },
  {
    id_fornecedor: "forn-3",
    id_predio: "predio-1",
    nome: "CleanCondo - Higienização",
    nif: "509887766",
    iban: "PT50 0018 0000 9988 7766 5544 3",
    categoria: "Limpeza de Áreas Comuns",
    morada: "Rua Direita do Massamá, 45, Sintra",
    contacto: "219 888 777",
    pessoa_contacto: "Maria Silva",
    email_contacto: "rosa.limpezas@cleancondo.pt",
    telemovel_direto: "961 112 233",
    data_nascimento: "1988-11-20",
    perfis_pwa: ["LIMPEZAS"],
    pwa_acesso_enviado: true,
    pwa_password_provisoria: "CleanPwa2026!"
  },
  {
    id_fornecedor: "forn-4",
    id_predio: "predio-1",
    nome: "Margarida Castro & Associados",
    nif: "504332211",
    iban: "PT50 0035 0000 1122 3344 5566 7",
    categoria: "Serviços Jurídicos e Contencioso",
    morada: "Avenida da Liberdade, 220, Lisboa",
    contacto: "213 400 500",
    pessoa_contacto: "Dra. Margarida Castro",
    email_contacto: "margarida.adv@contencioso.pt",
    telemovel_direto: "934 556 778",
    data_nascimento: "1979-03-25",
    perfis_pwa: ["JURIDICO"],
    pwa_acesso_enviado: true,
    pwa_password_provisoria: "AdvPwa2026!"
  }
];

export const initialFracoes: Fracao[] = [
  {
    id_fracao: "frac-1",
    id_predio: "predio-1",
    fracao_nome: "A",
    piso: "R/C Esq",
    permilagem: 150,
    tipologia: "Residencial",
    tipo_access: "Acesso Comum pelas Escadas",
    tem_garagem_spot: true,
    tem_arrecadacao_box: true,
    is_arrendada: true,
    administrador_interno: "Não",
    notificacao_preferencial: "Digital (E-mail e Mensagens Push)",
    proprietario: {
      nome: "Ana Silva",
      nif: "221230475",
      email: "ana.silva@gmail.com",
      tlm: "963456789",
      iban: "PT50 0035 0999 8888 7777 6666 5",
      titular_conta: "Ana Maria Silva",
      entidade_bancaria: "Caixa Geral de Depósitos",
      morada_alternativa: "Avenida da Liberdade 12, 4º Dto, Lisboa",
      foto: null,
      data_nascimento: "1988-04-12"
    },
    inquilino: {
      nome: "Ricardo Inquilino",
      email: "ricardo.loc@gmail.com",
      tlm: "929887766",
      nif: "255667788",
      foto: null
    },
    seguradora: "Tranquilidade Seguros",
    apolice_num: "TRQ-9988221",
    apolice_validade: "2026-08-15"
  },
  {
    id_fracao: "frac-2",
    id_predio: "predio-1",
    fracao_nome: "B",
    piso: "R/C Dto (Loja)",
    permilagem: 100,
    tipologia: "Loja Comercial",
    tipo_access: "Acesso Direto pelo Exterior sem Escadas",
    tem_garagem_spot: false,
    tem_arrecadacao_box: false,
    is_arrendada: false,
    administrador_interno: "Não",
    notificacao_preferencial: "Correio Postal (Físico)",
    proprietario: {
      nome: "Carlos Administrador",
      nif: "201334992",
      email: "carlos.adm@condomanager.pt",
      tlm: "912345678",
      iban: "PT50 0018 2222 3333 4444 5555 6",
      titular_conta: "Carlos Alberto Ferreira",
      entidade_bancaria: "Santander Totta",
      morada_alternativa: null,
      foto: null
    },
    inquilino: null
  },
  {
    id_fracao: "frac-3",
    id_predio: "predio-1",
    fracao_nome: "K",
    piso: "3º Esq",
    permilagem: 175,
    tipologia: "Residencial",
    tipo_access: "Acesso Comum pelas Escadas",
    tem_garagem_spot: true,
    tem_arrecadacao_box: true,
    is_arrendada: false,
    administrador_interno: "Sim",
    notificacao_preferencial: "Digital (E-mail e Mensagens Push)",
    proprietario: {
      nome: "José Carlos Alves Guerra",
      nif: "221230475",
      email: "jose.guerra@outlook.pt",
      tlm: "931223344",
      iban: "PT50 0003 9999 8888 1111 2222 3",
      titular_conta: "José Carlos Guerra",
      entidade_bancaria: "Millennium BCP",
      morada_alternativa: null,
      foto: null
    },
    inquilino: null
  }
];

export const initialAvisos: Aviso[] = [
  { id_aviso: "av-6699", id_predio: "predio-1", id_fracao: "frac-1", tipo: "Cota Ordinária", data: "2026-05-01", vencimento: "2026-05-15", descricao: "Quota de Condomínio Ordinária - Maio / 2026", valor: 41.94, estado: "Pendente" },
  { id_aviso: "av-6716", id_predio: "predio-1", id_fracao: "frac-1", tipo: "Fundo de Reserva", data: "2026-05-01", vencimento: "2026-05-15", descricao: "Quota do Fundo Comum de Reserva - Maio / 2026", valor: 4.19, estado: "Pendente" },
  { id_aviso: "av-3", id_predio: "predio-1", id_fracao: "frac-2", tipo: "Cota Ordinária", data: "2026-05-01", vencimento: "2026-05-15", descricao: "Quota de Condomínio Ordinária - Maio / 2026 (Com Desconto Loja)", valor: 19.57, estado: "Pendente" }
];

export const initialMovements: Movimento[] = [
  { id_mov: "mov-1", id_predio: "predio-1", id_conta: "cta-1", data: "2026-05-02", tipo: "Receita", valor: 48.93, descricao: "Pagamento Cota 3º Esq - José Guerra", categoria: "Quotas Ordinárias" }
];

export const initialReunioes: Reuniao[] = [
  { id_reuniao: "reu-1", id_predio: "predio-1", data: "2026-08-10", hora: "21:00", tema: "Assembleia Geral Ordinária", ordens_trabalho: "1. Aprovação de contas de 2025;\n2. Eleição de administração;\n3. Orçamento de manutenção do telhado.", estado: "Agendada" }
];

export const initialDocumentos: Documento[] = [
  // PASTA PAGA. QUOTAS (RECIBOS, RECIBOS QUOTAS EXTRA, NOTAS DE COBRANÇA POR ANO DE EXERCÍCIO)
  {
    id_doc: "doc-pp-2026-rec-1",
    id_predio: "predio-1",
    nome: "Recibo_QM_2026_01_Fracao_A.pdf",
    tipo: "Recibo",
    data_upload: "2026-01-08",
    tamanho: "320 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Recibos",
    descricao: "Recibo nº REC-2026-001 - Quota Mensal de Janeiro 2026 - Fração A (Piso 1 Esquerdo)",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2026-rec-2",
    id_predio: "predio-1",
    nome: "Recibo_QM_2026_02_Fracao_B.pdf",
    tipo: "Recibo",
    data_upload: "2026-02-05",
    tamanho: "315 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Recibos",
    descricao: "Recibo nº REC-2026-002 - Quota Mensal de Fevereiro 2026 - Fração B (Piso 1 Direito)",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2026-recextra-1",
    id_predio: "predio-1",
    nome: "Recibo_QE_Pintura_2026_Fracao_A.pdf",
    tipo: "Recibo Quotas extra",
    data_upload: "2026-03-15",
    tamanho: "340 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Recibos Quotas extra",
    descricao: "Recibo nº REC-2026-QE01 - Quota Extraordinária Obras de Pintura 2026 - Fração A",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2026-notacob-1",
    id_predio: "predio-1",
    nome: "Nota_Cobranca_AV-2026-001_Fracao_A.pdf",
    tipo: "Nota de Cobrança",
    data_upload: "2026-01-01",
    tamanho: "280 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Notas de cobrança",
    descricao: "Aviso nº AV-2026-001 - Nota de Cobrança Quota Janeiro 2026 - Fração A",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2026-notacob-2",
    id_predio: "predio-1",
    nome: "Nota_Cobranca_AV-2026-002_Fracao_B.pdf",
    tipo: "Nota de Cobrança",
    data_upload: "2026-01-01",
    tamanho: "285 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Notas de cobrança",
    descricao: "Aviso nº AV-2026-002 - Nota de Cobrança Quota Janeiro 2026 - Fração B",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2025-rec-1",
    id_predio: "predio-1",
    nome: "Recibo_QM_2025_12_Fracao_A.pdf",
    tipo: "Recibo",
    data_upload: "2025-12-10",
    tamanho: "310 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Recibos",
    descricao: "Recibo nº REC-2025-142 - Quota Mensal Dezembro 2025 - Fração A",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2025-recextra-1",
    id_predio: "predio-1",
    nome: "Recibo_QE_Impermeabilizacao_2025_Fracao_C.pdf",
    tipo: "Recibo Quotas extra",
    data_upload: "2025-10-20",
    tamanho: "330 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Recibos Quotas extra",
    descricao: "Recibo nº REC-2025-QE08 - Quota Extraordinária Impermeabilização 2025 - Fração C",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-pp-2025-notacob-1",
    id_predio: "predio-1",
    nome: "Nota_Cobranca_AV-2025-088_Fracao_A.pdf",
    tipo: "Nota de Cobrança",
    data_upload: "2025-12-01",
    tamanho: "275 KB",
    categoria: "Pasta Paga. Quotas",
    sub_pasta: "Notas de cobrança",
    descricao: "Aviso nº AV-2025-088 - Nota de Cobrança Quota Dezembro 2025 - Fração A",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Pasta Paga. Quotas",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  // ============================================================================
  // 📁 PASTA TEMPORÁRIA - 1 CÓPIA DE CADA DOCUMENTO DO SISTEMA (MARCA DE ÁGUA & VERIFICAÇÃO)
  // ============================================================================
  {
    id_doc: "doc-tmp-recibo-oficial-1",
    id_predio: "predio-1",
    nome: "Recibo_de_Pagamento_BR2_00195.pdf",
    tipo: "Recibo de Pagamento",
    data_upload: "2026-07-30",
    tamanho: "340 KB",
    categoria: "Recibo de Pagamento",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Recibo de Pagamento nº BR2 00195 referente a Quota Ordinária de Julho 2026 (32.14 €) e Fundo Comum de Reserva (3.21 €) da Fração A (R/C Esq) - Edifício Estrela da Barra.",
    visibilidade: "Público",
    autor: "Sistema CondoManager AI (Recibos)",
    tema: "Recibos & Quitações",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-tmp-notacob-oficial-1",
    id_predio: "predio-1",
    nome: "Nota_de_Cobranca_Mensal_BR2_00195.pdf",
    tipo: "Nota de Cobrança",
    data_upload: "2026-08-01",
    tamanho: "340 KB",
    categoria: "Nota de Cobrança Mensal",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Nota de Cobrança Mensal nº BR2 00195 emitida para liquidação de Quota Ordinária (32.14 €) e Fundo Comum de Reserva (3.21 €) da Fração A, com IBAN do condomínio (PT50 0033 0000 12345678901 02), referência individual da fração (BR2-FRA) para reconciliação automática por IA, email do prédio e instruções de envio de comprovativo via App.",
    visibilidade: "Público",
    autor: "Sistema CondoManager AI (Emissão Mensal)",
    tema: "Quotas & Cobranças",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-tmp-recibo-extra-1",
    id_predio: "predio-1",
    nome: "Recibo_Quota_Extraordinaria_Obras_FCR.pdf",
    tipo: "Recibo Quotas extra",
    data_upload: "2026-08-20",
    tamanho: "350 KB",
    categoria: "Recibo de Quota Extraordinária",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Recibo de quitação de quota extraordinária para obras de intervenção na fachada e reforço do Fundo Comum de Reserva com menção expressa à deliberação de assembleia.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Recibos & Quitações",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-tmp-ar-rececao-1",
    id_predio: "predio-1",
    nome: "Comprovativo_Aviso_Rececao_Carta_AR_CTT.pdf",
    tipo: "Comprovativo AR / CTT",
    data_upload: "2026-08-20",
    tamanho: "480 KB",
    categoria: "Recibo de Receção de Cartas Registadas (AR)",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Comprovativo e talão oficial de envio e receção de carta registada com Aviso de Receção (AR) CTT (Registo RF892134591PT), assinado pelo destinatário para instrução de prova judicial em contencioso.",
    visibilidade: "Público",
    autor: "Departamento Jurídico",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-tmp-prints-provas-1",
    id_predio: "predio-1",
    nome: "Registo_Prints_Conversas_WhatsApp_Emails.pdf",
    tipo: "Acervo Probatório Digital",
    data_upload: "2026-08-20",
    tamanho: "890 KB",
    categoria: "Fotografias & Prints de Conversas / E-mails",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Acervo probatório digital organizado para representação judicial: capturas de ecrã certificadas de trocas de mensagens via WhatsApp, relatórios de envio de e-mails com cabeçalhos técnicos e notificações push PWA.",
    visibilidade: "Público",
    autor: "Departamento Jurídico",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-tmp-dossie-processo-1",
    id_predio: "predio-1",
    nome: "Dossie_Constituicao_Processo_Judicial_Contencioso.pdf",
    tipo: "Peça Processual & Dossiê",
    data_upload: "2026-08-20",
    tamanho: "1.1 MB",
    categoria: "Constituição de Processo Judicial Completo",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Dossiê completo de constituição de processo judicial (Injunção BNI / Julgado de Paz / Tribunal de Comarca) contendo fundamentação de facto e direito, cálculo de capital e juros de mora e rol indexado de documentos comprovativos (Doc. 1 a Doc. 6).",
    visibilidade: "Público",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-1",
    id_predio: "predio-1",
    nome: "Declaracao_Condominio_Escritura_Nao_Divida.pdf",
    tipo: "Declaração de Condomínio",
    data_upload: "2026-08-14",
    tamanho: "420 KB",
    categoria: "Declaração de Condomínio para Escritura",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Declaração de Situação de Débitos / Não Dívida de Condomínio para instrução de Escritura Pública de Compra e Venda (Lei n.º 8/2022). Emissão com marca de água e logótipo oficial.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Declarações & Escrituras",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO", "AUDITOR", "CONTABILISTA"]
  },
  {
    id_doc: "doc-teste-2",
    id_predio: "predio-1",
    nome: "Relatorio_Prestacao_Contas_Balancete_2026.pdf",
    tipo: "Prestação de Contas",
    data_upload: "2026-08-14",
    tamanho: "580 KB",
    categoria: "Relatório de Prestação de Contas & Balancete",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Relatório Financeiro de Prestação de Contas, Balancete de Receitas/Despesas e Mapeamento do Fundo Comum de Reserva. Inclui mapa discriminado por fração com marca de água.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Relatórios & Contabilidade",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA", "AUDITOR"]
  },
  {
    id_doc: "doc-teste-3",
    id_predio: "predio-1",
    nome: "Relatorio_Vistorias_Limpezas_Manutencao.pdf",
    tipo: "Relatório Técnico",
    data_upload: "2026-08-14",
    tamanho: "610 KB",
    categoria: "Relatório de Vistorias, Limpezas e Manutenção",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Ficha de Vistoria Periódica de Equipamentos (Elevadores, Portões, Iluminação, Grupo Gerador, Extintores e Plano de Higienização de Escadas). Registado com carimbo e marca de água.",
    visibilidade: "Público",
    autor: "Equipa Técnica & Limpezas (Modo de Testes)",
    tema: "Vistorias & Manutenção",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO", "LIMPEZAS"]
  },
  {
    id_doc: "doc-teste-4",
    id_predio: "predio-1",
    nome: "Ficha_Individual_Condomino_Mapa_Fracoes.pdf",
    tipo: "Cadastro do Prédio",
    data_upload: "2026-08-14",
    tamanho: "490 KB",
    categoria: "Ficha Individual do Condómino & Mapa de Frações",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Matriz cadastral de todas as frações autónomas (A a F), identificação de condóminos, permilagens, contactos, e histórico individual de liquidação de quotas.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Cadastro & Frações",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-teste-5",
    id_predio: "predio-1",
    nome: "Convocatoria_Assembleia_Geral_Ordinaria.pdf",
    tipo: "Convocatória",
    data_upload: "2026-08-14",
    tamanho: "350 KB",
    categoria: "Convocatória de Assembleia Geral",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Convocatória oficial para Assembleia Geral de Condóminos nos termos dos artigos 1431º e 1432º do Código Civil, com Ordem do Dia e instruções de voto presencial e remoto.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Assembleias & Convocatórias",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-6",
    id_predio: "predio-1",
    nome: "Ata_Assembleia_Geral_Aprovacao_Contas.pdf",
    tipo: "Ata Oficial",
    data_upload: "2026-08-14",
    tamanho: "520 KB",
    categoria: "Ata de Assembleia Geral de Condóminos",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Ata da Assembleia Geral de Condóminos elaborada conforme a Lei n.º 8/2022, contendo deliberações sobre aprovação de contas, fundo de reserva, dotação de quotas e força executiva (Art. 1434º C.C.).",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Atas & Legislação",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-7",
    id_predio: "predio-1",
    nome: "Aviso_Cobranca_Notificacao_Quotas_Em_Atraso.pdf",
    tipo: "Aviso de Cobrança",
    data_upload: "2026-08-14",
    tamanho: "310 KB",
    categoria: "Aviso de Cobrança / Notificação de Quotas",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Nota oficial de cobrança e aviso prévio de liquidação de quotas ordinárias e extraordinárias com referências MB WAY / Multibanco e prazo limite de regularização.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Quotas & Cobranças",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-8",
    id_predio: "predio-1",
    nome: "Pedido_Orcamento_Propostas_Manutencao_Edificio.pdf",
    tipo: "Pedido de Orçamento",
    data_upload: "2026-08-14",
    tamanho: "440 KB",
    categoria: "Pedido de Orçamento & Propostas de Fornecedores",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Mapa comparativo de propostas e orçamentos para reparação do telhado e pintura de fachada com caderno de encargos e prazos de garantia emitidos por fornecedores.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Orçamentos & Obras",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO"]
  },
  {
    id_doc: "doc-teste-9",
    id_predio: "predio-1",
    nome: "Documentos_Judiciais_Notificacao_Contencioso.pdf",
    tipo: "Documento Judicial",
    data_upload: "2026-08-14",
    tamanho: "480 KB",
    categoria: "Documentos Judiciais & Notificação de Contencioso",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Notificação extrajudicial registada com aviso de receção para interpelação de condómino em mora e junção de certidão com força executiva nos termos do art. 1434º C.C.",
    visibilidade: "Público",
    autor: "Departamento Jurídico (Modo de Testes)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-10",
    id_predio: "predio-1",
    nome: "Email_Comunicacao_Oficial_Aviso_Avarias.pdf",
    tipo: "Comunicação Oficial",
    data_upload: "2026-08-14",
    tamanho: "290 KB",
    categoria: "E-mail & Comunicação Oficial do Condomínio",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Registo e cópia de e-mail enviado em massa com aviso de intervenção nos elevadores e desligamento temporário de água para trabalhos de manutenção urgente.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Comunicações & Notificações",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER"]
  },
  {
    id_doc: "doc-teste-11",
    id_predio: "predio-1",
    nome: "Parecer_Auditoria_Interna_Contabilidade.pdf",
    tipo: "Relatório de Auditoria",
    data_upload: "2026-08-14",
    tamanho: "510 KB",
    categoria: "Relatório de Auditoria Interna & Contabilidade",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Parecer técnico e auditoria às contas bancárias, reconciliação de movimentos por IA e verificação do cumprimento de retenções na fonte e obrigações fiscais.",
    visibilidade: "Público",
    autor: "Dr. António Auditor (Modo de Testes)",
    tema: "Auditoria & Finanças",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "AUDITOR", "CONTABILISTA"]
  },
  {
    id_doc: "doc-teste-12",
    id_predio: "predio-1",
    nome: "Comprovativo_Pagamento_Recibo_Conciliado.pdf",
    tipo: "Comprovativo / Recibo",
    data_upload: "2026-08-14",
    tamanho: "320 KB",
    categoria: "Comprovativo de Pagamento & Recibo Otimizado",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Comprovativo bancário de pagamento de quota com validação automática por IA e recibo oficial numerado com indicação de liquidação total e marca de água.",
    visibilidade: "Público",
    autor: "Carlos Administrador (Modo de Testes)",
    tema: "Recibos & Conciliação",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA"]
  },
  {
    id_doc: "doc-teste-fatura-ocr-1",
    id_predio: "predio-1",
    nome: "Fatura_Fornecedor_OTIS_Elevadores_OCR.pdf",
    tipo: "Fatura de Despesa",
    data_upload: "2026-08-20",
    tamanho: "410 KB",
    categoria: "Fatura de Despesa / Leitura OCR",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Fatura digital de manutenção preventiva mensal dos ascensores com extração ótica OCR de NIF, Valor Total, taxa de IVA e lançamento validado em despesas.",
    visibilidade: "Administração",
    autor: "OTIS Elevadores (Lançamento OCR)",
    tema: "Faturas & Fornecedores",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "CONTABILISTA", "AUDITOR"]
  },
  {
    id_doc: "doc-teste-injuncao-bni",
    id_predio: "predio-1",
    nome: "Requerimento_Injuncao_BNI_Certidao_Divida.pdf",
    tipo: "Requerimento Judicial",
    data_upload: "2026-08-20",
    tamanho: "490 KB",
    categoria: "Requerimento de Injunção no BNI / Tribunal",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Formulário e certidão de dívida com força executiva para injunção perante o Balcão Nacional de Injunções nos termos da legislação processual civil.",
    visibilidade: "Administração",
    autor: "Departamento Jurídico",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-regulamento-interno",
    id_predio: "predio-1",
    nome: "Regulamento_Interno_Oficial_Edificio.pdf",
    tipo: "Regulamento do Prédio",
    data_upload: "2026-08-20",
    tamanho: "520 KB",
    categoria: "Regulamento Interno do Edifício",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Regulamento do Condomínio com normas de convivência, horários de ruído, regras de utilização das garagens, arrecadações e áreas comuns.",
    visibilidade: "Público",
    autor: "Administração do Condomínio",
    tema: "Regulamentos & Estatutos",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },
  {
    id_doc: "doc-teste-estatutos-predio",
    id_predio: "predio-1",
    nome: "Estatutos_Propriedade_Horizontal_Edificio.pdf",
    tipo: "Estatutos do Prédio",
    data_upload: "2026-08-20",
    tamanho: "460 KB",
    categoria: "Estatutos da Propriedade Horizontal",
    sub_pasta: "📁 Pasta Temporária - Teste & Verificação (Marca de Água)",
    descricao: "Estatutos estruturais do edifício em regime de propriedade horizontal com fixação de órgãos de gestão, quóruns deliberativos e direitos reais.",
    visibilidade: "Público",
    autor: "Administração do Condomínio",
    tema: "Regulamentos & Estatutos",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },

  // ============================================================================
  // ⚖️ PASTA DE ARQUIVO DEDICADA: PROCESSOS JURÍDICOS & CONTENCIOSO
  // ============================================================================
  {
    id_doc: "doc-proc-1-ata",
    id_predio: "predio-1",
    nome: "Proc_001_Doc1_Ata_Assembleia_Forca_Executiva.pdf",
    tipo: "Título Executivo / Ata",
    data_upload: "2026-06-15",
    tamanho: "520 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Doc. 1: Ata nº 14 da Assembleia Geral Ordinária com Força Executiva nos termos do Art. 1434º do Código Civil.",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-1-extrato",
    id_predio: "predio-1",
    nome: "Proc_001_Doc2_Extrato_Conta_Corrente_Divida.pdf",
    tipo: "Extrato de Dívida",
    data_upload: "2026-06-15",
    tamanho: "340 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Doc. 2: Extrato Analítico de Conta-Corrente com demonstração dos avisos em mora e juros de mora legais (4%).",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-1-carta-ar",
    id_predio: "predio-1",
    nome: "Proc_001_Doc3_Carta_Notificacao_AR_Interpelacao.pdf",
    tipo: "Notificação CTT AR",
    data_upload: "2026-06-25",
    tamanho: "290 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Doc. 3: Carta Registada de Notificação e Interpelação com Aviso de Receção (Registo CTT RF892134591PT).",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-1-recibo-ar",
    id_predio: "predio-1",
    nome: "Proc_001_Doc4_Recibo_Rececao_Carta_AR_CTT_RF892134591PT.pdf",
    tipo: "Recibo AR Assinado",
    data_upload: "2026-06-25",
    tamanho: "620 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Doc. 4: Aviso de Receção (AR) CTT assinado pelo réu Dr. João Silva, comprovando a receção em 20/06/2026.",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-1-prints",
    id_predio: "predio-1",
    nome: "Proc_001_Doc5_Prints_WhatsApp_Emails_Interpelacao.pdf",
    tipo: "Prints & Provas Digitais",
    data_upload: "2026-06-15",
    tamanho: "780 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Doc. 5: Capturas de ecrã certificadas de conversas de WhatsApp e emails de cobrança com confirmação de leitura.",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-1-dossie-completo",
    id_predio: "predio-1",
    nome: "Proc_001_Dossie_Completo_Apresentacao_Tribunal.pdf",
    tipo: "Dossiê Judicial Completo",
    data_upload: "2026-07-10",
    tamanho: "1.5 MB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/001 (Fração A) • Dossiê Oficial Unificado com Capa, Petição Inicial/Requerimento BNI, Quadro de Créditos e Rol de Documentos.",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },
  {
    id_doc: "doc-proc-2-foto",
    id_predio: "predio-1",
    nome: "Proc_002_Doc1_Fotografia_Infracao_Fachada.jpg",
    tipo: "Fotografia de Infração",
    data_upload: "2026-07-02",
    tamanho: "1.4 MB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/002 (Fração D) • Doc. 1: Fotografia HD pericial do fecho não autorizado da varanda na fachada exterior.",
    visibilidade: "Administração",
    autor: "Equipa de Vistorias Técnicas",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO", "TECNICO"]
  },
  {
    id_doc: "doc-proc-2-recibo-ar",
    id_predio: "predio-1",
    nome: "Proc_002_Doc2_Aviso_Rececao_Embargo_CTT.pdf",
    tipo: "Recibo AR Embargo",
    data_upload: "2026-07-12",
    tamanho: "540 KB",
    categoria: "Processos Jurídicos & Contencioso",
    sub_pasta: "⚖️ Processos Jurídicos & Contencioso",
    descricao: "Proc. PROC-2026/002 (Fração D) • Doc. 2: Aviso de Receção da notificação admonitória de embargo extrajudicial expedido pelos CTT.",
    visibilidade: "Administração",
    autor: "Dra. Filipa Antunes (Advogada)",
    tema: "Contencioso & Jurídico",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },

  // MANUAIS E INSTRUÇÕES PWA & DESKTOP (PASTA DEDICADA)
  {
    id_doc: "doc-manual-1",
    id_predio: "predio-1",
    nome: "Manual_Perfis_Menus_Capacidades_CondoManager.pdf",
    tipo: "Instruções & Manuais",
    data_upload: "2026-07-23",
    tamanho: "1.8 MB",
    categoria: "Instruções PWA & Desktop",
    sub_pasta: "Instruções PWA & Desktop",
    descricao: "Manual oficial e matriz de permissões detalhada por perfil para navegação via Web Browser Desktop e App PWA Mobile.",
    visibilidade: "Público",
    autor: "CondoManager AI System",
    tema: "Instruções PWA & Desktop",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO", "LIMPEZAS", "JURIDICO", "AUDITOR", "CONTABILISTA"]
  },
  {
    id_doc: "doc-manual-2",
    id_predio: "predio-1",
    nome: "Instrucoes_Instalacao_Uso_PWA_Mobile.pdf",
    tipo: "Instruções & Manuais",
    data_upload: "2026-07-23",
    tamanho: "1.4 MB",
    categoria: "Instruções PWA & Desktop",
    sub_pasta: "Instruções PWA & Desktop",
    descricao: "Guia passo-a-passo de instalação da PWA no telemóvel (iOS/Android), gestão de notificações push e atalhos offline.",
    visibilidade: "Público",
    autor: "CondoManager AI System",
    tema: "Instruções PWA & Desktop",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO", "LIMPEZAS", "JURIDICO", "AUDITOR", "CONTABILISTA"]
  },
  {
    id_doc: "doc-manual-3",
    id_predio: "predio-1",
    nome: "Manual_Utilizador_Browser_Desktop.pdf",
    tipo: "Instruções & Manuais",
    data_upload: "2026-07-23",
    tamanho: "1.6 MB",
    categoria: "Instruções PWA & Desktop",
    sub_pasta: "Instruções PWA & Desktop",
    descricao: "Guia completo de navegação desktop por colunas, arquivo digital com IA, conciliação bancária e módulo de assembleias.",
    visibilidade: "Público",
    autor: "CondoManager AI System",
    tema: "Instruções PWA & Desktop",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO", "LIMPEZAS", "JURIDICO", "AUDITOR", "CONTABILISTA"]
  },
  {
    id_doc: "doc-manual-4",
    id_predio: "predio-1",
    nome: "Guia_Sintetizado_Funcionalidades_AI_CondoManager.pdf",
    tipo: "Instruções & Manuais",
    data_upload: "2026-07-24",
    tamanho: "2.1 MB",
    categoria: "Instruções PWA & Desktop",
    sub_pasta: "Instruções PWA & Desktop",
    descricao: "Mapeamento completo e exaustivo de todas as funcionalidades, menus, sub-menus, módulos de Inteligência Artificial (IA), leitor ótico OCR, câmara WebP, gravador de áudio e perfis de utilizador do CondoManager AI.",
    visibilidade: "Público",
    autor: "CondoManager AI System",
    tema: "Instruções PWA & Desktop",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO", "LIMPEZAS", "JURIDICO", "AUDITOR", "CONTABILISTA"]
  },
  // 2026 DOCUMENTOS
  {
    id_doc: "doc-1",
    id_predio: "predio-1",
    nome: "Ata_Assembleia_Geral_Ordinaria_2025.pdf",
    tipo: "Atas",
    data_upload: "2025-01-15",
    tamanho: "1.2 MB",
    categoria: "Atas",
    descricao: "Ata oficial da Assembleia Geral Ordinária realizada para eleição da administração e aprovação de contas de 2024.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Atas & Convocatórias",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },
  {
    id_doc: "doc-2",
    id_predio: "predio-1",
    nome: "Apolice_Multirriscos_Predio_2026.pdf",
    tipo: "Seguros do prédio",
    data_upload: "2026-01-05",
    tamanho: "3.4 MB",
    categoria: "Seguros do prédio",
    descricao: "Apólice de Seguro Multirriscos Condomínio Allianz - Cobertura global de paredes e áreas comuns.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Seguros & Apólices",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA", "JURIDICO"]
  },
  {
    id_doc: "doc-3",
    id_predio: "predio-1",
    nome: "Regulamento_Interno_Condominio_Revisado.pdf",
    tipo: "Regulamentos",
    data_upload: "2024-03-20",
    tamanho: "850 KB",
    categoria: "Regulamentos",
    descricao: "Regulamento de condomínio em vigor, detalhando direitos, deveres, regras de ruído e utilização de espaços comuns.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Regulamentos & Legal",
    ano: "2024",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "JURIDICO"]
  },
  {
    id_doc: "doc-4",
    id_predio: "predio-1",
    nome: "Contrato_Manutencao_Elevadores_OTIS.pdf",
    tipo: "Serviços",
    data_upload: "2025-06-12",
    tamanho: "1.8 MB",
    categoria: "Serviços",
    descricao: "Contrato de Prestação de Serviços de Manutenção Preventiva dos Elevadores (OTIS).",
    visibilidade: "Administração",
    autor: "Carlos Administrador",
    tema: "Regulamentos & Legal",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "TECNICO", "JURIDICO"]
  },
  {
    id_doc: "doc-5",
    id_predio: "predio-1",
    nome: "Orcamento_Geral_Aprovado_Exercicio_2026.pdf",
    tipo: "Orçamentos",
    data_upload: "2026-01-10",
    tamanho: "2.1 MB",
    categoria: "Orçamentos",
    descricao: "Plano orçamental detalhado aprovado para o ano corrente, com distribuição de quotas mensais por fração.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Faturas & Recibos",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA", "AUDITOR"]
  },
  {
    id_doc: "doc-6",
    id_predio: "predio-1",
    nome: "Fatura_Reparacao_Infiltracao_Canalizacao.pdf",
    tipo: "Reparações",
    data_upload: "2026-04-18",
    tamanho: "650 KB",
    categoria: "Reparações",
    descricao: "Fatura detalhada dos trabalhos urgentes de canalização para estancar infiltração no piso 1.",
    visibilidade: "Administração",
    autor: "Carlos Administrador",
    tema: "Faturas & Recibos",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "CONTABILISTA", "TECNICO"]
  },
  {
    id_doc: "doc-7",
    id_predio: "predio-1",
    nome: "Relatorio_Contas_Mensal_Dezembro_2025.pdf",
    tipo: "Relatórios de contas",
    data_upload: "2026-01-01",
    tamanho: "1.5 MB",
    categoria: "Relatórios de contas",
    descricao: "Relatório de encerramento do exercício financeiro do ano anterior, balancete e saldos finais bancários.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Relatórios & Auditorias",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "CONTABILISTA", "AUDITOR"]
  },
  {
    id_doc: "doc-8",
    id_predio: "predio-1",
    nome: "Parecer_Auditoria_Independente_2025.pdf",
    tipo: "Relatórios de contas",
    data_upload: "2026-02-10",
    tamanho: "2.3 MB",
    categoria: "Relatórios de contas",
    descricao: "Parecer de auditoria aos movimentos financeiros e contas de fundo de reserva do condomínio.",
    visibilidade: "Público",
    autor: "Dr. António Auditor",
    tema: "Relatórios & Auditorias",
    ano: "2025",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "AUDITOR"]
  },
  {
    id_doc: "doc-9",
    id_predio: "predio-1",
    nome: "Folha_Digital_Limpeza_Higienizacao_Maio_2026.pdf",
    tipo: "Serviços",
    data_upload: "2026-05-30",
    tamanho: "920 KB",
    categoria: "Serviços",
    descricao: "Registo quinzenal assinado dos trabalhos de desinfeção, lavagem de halls e verificação de lâmpadas.",
    visibilidade: "Público",
    autor: "Maria Silva (Limpezas)",
    tema: "Higienização & Limpezas",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "LIMPEZAS"]
  },
  {
    id_doc: "doc-10",
    id_predio: "predio-1",
    nome: "Notificacao_Judicial_Cobranca_Proprietario_Inadimplente.pdf",
    tipo: "Regulamentos",
    data_upload: "2026-03-12",
    tamanho: "1.1 MB",
    categoria: "Regulamentos",
    descricao: "Minuta de interpelação e citação judicial enviada ao departamento jurídico para cobrança de frações em mora.",
    visibilidade: "Administração",
    autor: "Dra. Margarida Jurídico",
    tema: "Regulamentos & Legal",
    ano: "2026",
    tipo_arquivo: "documento",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "JURIDICO"]
  },

  // FOTOGRAFIAS DO ARQUIVO
  {
    id_doc: "foto-1",
    id_predio: "predio-1",
    nome: "Vistoria_Cobertura_E_Telhado_Pos_Tempestade.jpg",
    tipo: "Fotografia",
    data_upload: "2026-04-10",
    tamanho: "2.8 MB",
    categoria: "Vistorias Técnicas",
    descricao: "Inspecção fotográfica detalhada ao estado dos algerozes e telhas da cobertura após intempérie.",
    visibilidade: "Público",
    autor: "Eng. Rui Melo (Técnico)",
    tema: "Vistorias Técnicas",
    ano: "2026",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO"]
  },
  {
    id_doc: "foto-2",
    id_predio: "predio-1",
    nome: "Reparacao_Substituicao_Quadro_Eletrico_Garagem.jpg",
    tipo: "Fotografia",
    data_upload: "2026-03-22",
    tamanho: "3.1 MB",
    categoria: "Obras & Reparações",
    descricao: "Fotografia do novo disjuntor diferencial instalado no quadro elétrico das garagens subterrâneas.",
    visibilidade: "Público",
    autor: "Eng. Rui Melo (Técnico)",
    tema: "Obras & Reparações",
    ano: "2026",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "TECNICO"]
  },
  {
    id_doc: "foto-3",
    id_predio: "predio-1",
    nome: "Higienizacao_Lavagem_Garagens_Piso_Minus_1.jpg",
    tipo: "Fotografia",
    data_upload: "2026-05-15",
    tamanho: "2.4 MB",
    categoria: "Higienização & Limpezas",
    descricao: "Comprovativo fotográfico da lavagem mecânica a alta pressão do piso -1 das garagens.",
    visibilidade: "Público",
    autor: "Maria Silva (Limpezas)",
    tema: "Higienização & Limpezas",
    ano: "2026",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER", "LIMPEZAS"]
  },
  {
    id_doc: "foto-4",
    id_predio: "predio-1",
    nome: "Registo_Defeito_Fissura_Parede_Externa_Bloco_B.jpg",
    tipo: "Fotografia",
    data_upload: "2025-11-20",
    tamanho: "1.9 MB",
    categoria: "Avarias Reportadas",
    descricao: "Foto do registo de fissura na fachada lateral perto da janela da fração 2º B para análise da garantia de obra.",
    visibilidade: "Administração",
    autor: "Carlos Administrador",
    tema: "Avarias Reportadas",
    ano: "2025",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "TECNICO", "JURIDICO"]
  },
  {
    id_doc: "foto-5",
    id_predio: "predio-1",
    nome: "Fachada_Principal_Edificio_Patrimonio.jpg",
    tipo: "Fotografia",
    data_upload: "2024-06-01",
    tamanho: "4.2 MB",
    categoria: "Património do Edifício",
    descricao: "Fotografia panorâmica de alta resolução da entrada principal do edifício e iluminação do átrio.",
    visibilidade: "Público",
    autor: "Carlos Administrador",
    tema: "Património do Edifício",
    ano: "2024",
    tipo_arquivo: "fotografia",
    url_foto: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    relevancia_perfis: ["ADMIN", "EMPRESA_GESTORA", "USER"]
  }
];

export const initialOcorrencias: Ocorrencia[] = [
  { 
    id_ocorr: "oc-1", 
    id_predio: "predio-1", 
    id_fracao: "frac-1", // Fração A (Ana Silva)
    descricao: "Infiltração grave no teto da casa de banho principal, vinda do andar superior.", 
    data: "2026-05-01", 
    estado: "Em Reparação", 
    medidas_tomadas: "Técnico da empresa HydroStop localizou rotura na junta da banheira do 1º andar. Procedeu-se à substituição das tubagens danificadas.", 
    fotos: [],
    categoria: "Infiltrações",
    tecnico_atribuido: "HydroStop Canalizações, Lda."
  },
  { 
    id_ocorr: "oc-2", 
    id_predio: "predio-1", 
    id_fracao: "frac-2", // Fração B (Bruno Costa)
    descricao: "Lâmpadas tubulares do patamar do 2º andar estão a piscar e uma fundiu por completo.", 
    data: "2026-05-10", 
    estado: "Concluída", 
    medidas_tomadas: "Substituídas as lâmpadas fluorescentes antigas por novas lâmpadas LED tubulares de alta eficiência.", 
    fotos: [],
    categoria: "Eletricidade",
    tecnico_atribuido: "EletroRápido Reparações"
  },
  { 
    id_ocorr: "oc-3", 
    id_predio: "predio-1", 
    id_fracao: "frac-3", // Fração C (Clara Duarte)
    descricao: "O elevador nº 2 (lado direito) apresenta ruído anormal durante a subida entre o 3º e o 5º piso.", 
    data: "2026-05-18", 
    estado: "Orçamento", 
    medidas_tomadas: "Contacto estabelecido com a Otis Elevadores. Técnico realizou diagnóstico técnico preliminar e aguarda aprovação da proposta comercial para substituição dos cabos de tração.", 
    fotos: [],
    categoria: "Elevadores",
    tecnico_atribuido: "OTIS Elevadores Portugal"
  },
  { 
    id_ocorr: "oc-4", 
    id_predio: "predio-1", 
    id_fracao: "frac-1", // Fração A
    descricao: "Portão automático de acesso à garagem comum do condomínio bloqueia a meio da abertura.", 
    data: "2026-05-20", 
    estado: "A aguardar", 
    medidas_tomadas: "Registado no sistema e aguardando deslocação do piquete técnico de automatismos.", 
    fotos: [],
    categoria: "Serralharia",
    tecnico_atribuido: "PortasFortes Segurança"
  }
];

export const initialGestoresCarteira: GestorCarteira[] = [
  {
    id_gestor: "gestor-1",
    nome: "Dra. Filipa Vasconcelos",
    tlm: "912 345 678",
    email: "filipa.v@gestaoforte.pt",
    predios_atribuidos: ["predio-1"],
    perfil: "GESTOR",
    status_acesso: "ATIVO",
    password_provisoria: "GestorForte2026!",
    email_boas_vindas_enviado: true,
    data_atribuicao: "2026-01-15",
    foto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80"
  },
  {
    id_gestor: "gestor-2",
    nome: "Carlos Lima",
    tlm: "912 876 543",
    email: "carlos.l@gestaoforte.pt",
    predios_atribuidos: ["predio-1"],
    perfil: "ADMIN",
    status_acesso: "ATIVO",
    password_provisoria: "AdminLima2026!",
    email_boas_vindas_enviado: true,
    data_atribuicao: "2026-02-01",
    foto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80"
  }
];

export const initialEmpresaGestoraConfig: EmpresaGestoraConfig = {
  nome_empresa: "Gestão Forte Administrações Lda",
  nif: "509483726",
  email_corporativo: "contacto@gestaoforte.pt",
  telefone: "210 987 654",
  website: "https://www.gestaoforte.pt",
  email_autoresponder_principal: "CONDOMINIO", // Padrão: E-mail do condomínio para personalização local
  email_gestao_ia: "CONDOMINIO", // Padrão: E-mail do condomínio para triagem inteligente
  gestores: initialGestoresCarteira
};

export const processosJudiciaisIniciais: ProcessoJuridico[] = [
  {
    id_processo: "PROC-2026/001-JUR",
    id_predio: "predio-1",
    id_fracao: "frac-1",
    fracao_nome: "Fração A - 1º Dto",
    nome_reu: "Dr. João Silva",
    nif_reu: "123456789",
    tipo_processo: "FALTA_PAGAMENTO_QUOTAS",
    titulo_processo: "Ação Executiva para Cobrança de Quotas em Atraso (Art. 1434º C.C.)",
    descricao_resumo: "Incumprimento continuado no pagamento de quotas ordinárias e dotações para o FCR relativas aos meses de Março a Julho de 2026. Tentativas de regularização extrajudicial frustradas após interpelação por carta registada com aviso de receção.",
    valor_divida_capital: 485.00,
    valor_juros_mora: 29.10,
    taxa_juros: 4.0,
    custas_processuais_estimadas: 51.00,
    valor_total_pedido: 565.10,
    tribunal_competente: "Balcão Nacional de Injunções (BNI) / Julgado de Paz de Lisboa",
    fase_processual: "INJUNCAO_BNI",
    data_abertura: "2026-06-15",
    data_ultima_atualizacao: "2026-08-20",
    mandatario_responsavel: "Dra. Filipa Antunes (Advogada da Administração)",
    pasta_arquivo_digital_nome: "⚖️ Processos Jurídicos & Contencioso",
    provas: [
      {
        id_prova: "prv-101",
        id_processo: "PROC-2026/001-JUR",
        tipo: "ATA_ASSEMBLEIA_TITULO_EXECUTIVO",
        titulo: "Ata nº 14 da Assembleia Geral Ordinária (Título Executivo Art. 1434º C.C.)",
        descricao: "Deliberação de aprovação do orçamento anual, fixação do valor das quotas ordinárias de 48,50 €/mês e autorização expressa à administração para recurso à via judicial em caso de mora superior a 60 dias.",
        data_documento: "2026-01-15",
        data_adicao: "2026-06-15",
        numero_documento_ordem: 1,
        ficheiro_nome: "Proc_001_Doc1_Ata_Assembleia_Forca_Executiva.pdf",
        tamanho: "520 KB",
        tipo_ficheiro: "pdf",
        destinatario: "Assembleia Geral de Condóminos",
        observacoes_juridicas: "Título executivo dotado de força bastante nos termos do n.º 1 do art. 1434.º do Código Civil e Art. 6.º do Decreto-Lei n.º 268/94.",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-102",
        id_processo: "PROC-2026/001-JUR",
        tipo: "EXTRATO_CONTA_CORRENTE_DIVIDA",
        titulo: "Extrato Analítico de Conta-Corrente & Mapa Discriminado de Débitos",
        descricao: "Discriminação detalhada dos avisos de cobrança pendentes (AV-2026-012 a AV-2026-016), datas de vencimento, juros de mora calculados à taxa legal de 4% ao ano e despesas de cobrança.",
        data_documento: "2026-06-10",
        data_adicao: "2026-06-15",
        numero_documento_ordem: 2,
        ficheiro_nome: "Proc_001_Doc2_Extrato_Conta_Corrente_Divida.pdf",
        tamanho: "340 KB",
        tipo_ficheiro: "pdf",
        destinatario: "Dr. João Silva (Fração A)",
        observacoes_juridicas: "Demonstração analítica de liquidação e certeza do crédito exigido.",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-103",
        id_processo: "PROC-2026/001-JUR",
        tipo: "RECIBO_RECECAO_CARTA_AR",
        titulo: "Talão de Registo CTT e Recibo de Notificação Extrajudicial",
        descricao: "Comprovativo de envio de carta registada com aviso de receção para a morada oficial da fração, concedendo prazo suplementar improrrogável de 15 dias para liquidação voluntária.",
        data_documento: "2026-06-18",
        data_adicao: "2026-06-25",
        numero_documento_ordem: 3,
        ficheiro_nome: "Proc_001_Doc3_Carta_Notificacao_AR_Interpelacao.pdf",
        tamanho: "290 KB",
        tipo_ficheiro: "pdf",
        codigo_rastreio_ctt: "RF892134591PT",
        data_entrega_ctt: "2026-06-20",
        destinatario: "Dr. João Silva - Edifício Rossio",
        observacoes_juridicas: "Interpelação admonitória que constitui o devedor em mora plena (Art. 804º e 805º C.C.).",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-104",
        id_processo: "PROC-2026/001-JUR",
        tipo: "RECIBO_RECECAO_CARTA_AR",
        titulo: "Aviso de Receção (AR) CTT Assinado pelo Requerido (Recibo de Entrega)",
        descricao: "Digitalização frente e verso do modelo oficial CTT de Aviso de Receção com carimbo postal de entrega datado de 20/06/2026 e assinatura do próprio condómino.",
        data_documento: "2026-06-20",
        data_adicao: "2026-06-25",
        numero_documento_ordem: 4,
        ficheiro_nome: "Proc_001_Doc4_Recibo_Rececao_Carta_AR_CTT_RF892134591PT.pdf",
        tamanho: "620 KB",
        tipo_ficheiro: "imagem",
        codigo_rastreio_ctt: "RF892134591PT",
        data_entrega_ctt: "2026-06-20",
        url_preview: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80",
        destinatario: "Dr. João Silva (Assinado pelo próprio)",
        observacoes_juridicas: "Prova irrefutável de receção e conhecimento da interpelação.",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-105",
        id_processo: "PROC-2026/001-JUR",
        tipo: "PRINT_CONVERSA_WHATSAPP",
        titulo: "Prints Fotográficos de Conversas WhatsApp & Notificações Eletrónicas",
        descricao: "Capturas de ecrã autenticadas da troca de mensagens com o condómino através do WhatsApp e envio de referências de pagamento MB WAY nos dias 02/05/2026, 15/05/2026 e 01/06/2026, confirmando leitura (double check azul).",
        data_documento: "2026-06-01",
        data_adicao: "2026-06-15",
        numero_documento_ordem: 5,
        ficheiro_nome: "Proc_001_Doc5_Prints_WhatsApp_Emails_Interpelacao.pdf",
        tamanho: "780 KB",
        tipo_ficheiro: "imagem",
        url_preview: "https://images.unsplash.com/photo-1611746872915-64382b5c76da?auto=format&fit=crop&w=800&q=80",
        destinatario: "Contacto Móvel +351 912 345 678",
        observacoes_juridicas: "Meio complementar de prova da comunicação direta e conhecimento da obrigação.",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-106",
        id_processo: "PROC-2026/001-JUR",
        tipo: "PRINT_EMAIL_COMUNICACAO",
        titulo: "Print do Cabeçalho e Relatório de Entrega de E-mail Certificado",
        descricao: "Registo do servidor de correio eletrónico com o envio do extrato de conta-corrente e comprovativo de entrega no endereço joao.silva@email.com.",
        data_documento: "2026-06-05",
        data_adicao: "2026-06-15",
        numero_documento_ordem: 6,
        ficheiro_nome: "Proc_001_Doc6_Print_Email_Comprovativo_Envio.pdf",
        tamanho: "310 KB",
        tipo_ficheiro: "imagem",
        url_preview: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&w=800&q=80",
        destinatario: "joao.silva@email.com",
        observacoes_juridicas: "Prova documental nos termos do Art. 362º e seguintes do Código Civil.",
        arquivado_no_arquivo_digital: true
      }
    ],
    historico_tramitacao: [
      {
        id_fase: "fase-1",
        data_hora: "2026-06-01 10:00",
        fase: "Detecção de Incumprimento & Alerta",
        descricao: "Fração A atinge 5 meses consecutivos de incumprimento no valor global de 485,00 €.",
        responsavel: "Sistema Automático CondoManager AI"
      },
      {
        id_fase: "fase-2",
        data_hora: "2026-06-18 14:30",
        fase: "Envio de Carta Registada com AR",
        descricao: "Expedição da notificação admonitória via CTT Registo RF892134591PT com concessão de 15 dias.",
        responsavel: "Carlos Administrador"
      },
      {
        id_fase: "fase-3",
        data_hora: "2026-06-20 11:15",
        fase: "Entrega do Aviso de Receção (AR)",
        descricao: "Aviso de Receção assinado pelo condómino e recebido pela administração.",
        responsavel: "CTT Correios de Portugal"
      },
      {
        id_fase: "fase-4",
        data_hora: "2026-07-10 16:00",
        fase: "Submissão de Requerimento de Injunção",
        descricao: "Entrada do requerimento de injunção no Balcão Nacional de Injunções (BNI) com junção de todas as provas organizadas.",
        responsavel: "Dra. Filipa Antunes"
      }
    ]
  },
  {
    id_processo: "PROC-2026/002-JUR",
    id_predio: "predio-1",
    id_fracao: "frac-4",
    fracao_nome: "Fração D - 2º Dto",
    nome_reu: "Maria Helena Santos",
    nif_reu: "456789012",
    tipo_processo: "OBRAS_NAO_AUTORIZADAS",
    titulo_processo: "Ação de Embargo e Reposição da Traça Arquitetónica (Art. 1422º C.C.)",
    descricao_resumo: "Instalação de caixilharia de alumínio não aprovada e fecho de varanda na fachada exterior frontal sem prévia autorização da Assembleia de Condóminos, violando a linha arquitetónica do edifício.",
    valor_divida_capital: 0.00,
    valor_juros_mora: 0.00,
    taxa_juros: 0.0,
    custas_processuais_estimadas: 250.00,
    valor_total_pedido: 250.00,
    tribunal_competente: "Julgado de Paz de Lisboa / Tribunal Judicial de Comarca",
    fase_processual: "PRE_CONTENCIOSO_NOTIFICACAO",
    data_abertura: "2026-07-02",
    data_ultima_atualizacao: "2026-08-15",
    mandatario_responsavel: "Dra. Filipa Antunes (Advogada)",
    pasta_arquivo_digital_nome: "⚖️ Processos Jurídicos & Contencioso",
    provas: [
      {
        id_prova: "prv-201",
        id_processo: "PROC-2026/002-JUR",
        tipo: "FOTOGRAFIA_DANO_INFRACAO",
        titulo: "Fotografias HD da Fachada com Caixilharia Não Autorizada",
        descricao: "Registo fotográfico de alta resolução evidenciando o fecho da varanda com cor e material discordante do padrão do edifício.",
        data_documento: "2026-07-01",
        data_adicao: "2026-07-02",
        numero_documento_ordem: 1,
        ficheiro_nome: "Proc_002_Doc1_Fotografia_Infracao_Fachada.jpg",
        tamanho: "1.4 MB",
        tipo_ficheiro: "imagem",
        url_preview: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
        observacoes_juridicas: "Prova pericial/fotográfica de alteração da linha arquitetónica (Art. 1422º n.º 2 al. a) C.C.).",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-202",
        id_processo: "PROC-2026/002-JUR",
        tipo: "RECIBO_RECECAO_CARTA_AR",
        titulo: "Aviso de Receção (AR) CTT - Notificação de Embargo Extrajudicial",
        descricao: "Aviso de receção de carta registada interpelando para paragem imediata da obra e reposição da traça original em 30 dias.",
        data_documento: "2026-07-08",
        data_adicao: "2026-07-12",
        numero_documento_ordem: 2,
        ficheiro_nome: "Proc_002_Doc2_Aviso_Rececao_Embargo_CTT.pdf",
        tamanho: "540 KB",
        tipo_ficheiro: "pdf",
        codigo_rastreio_ctt: "RF892477123PT",
        data_entrega_ctt: "2026-07-10",
        destinatario: "Maria Helena Santos",
        observacoes_juridicas: "Notificação formal para cessação da atividade ilícita.",
        arquivado_no_arquivo_digital: true
      },
      {
        id_prova: "prv-203",
        id_processo: "PROC-2026/002-JUR",
        tipo: "PRINT_EMAIL_COMUNICACAO",
        titulo: "Prints de Troca de E-mails com Notificação da Administração",
        descricao: "Prints dos e-mails trocados onde a condómina reconhece a realização da intervenção sem consulta à Assembleia Geral.",
        data_documento: "2026-07-15",
        data_adicao: "2026-07-16",
        numero_documento_ordem: 3,
        ficheiro_nome: "Proc_002_Doc3_Prints_Emails_Reconhecimento.pdf",
        tamanho: "410 KB",
        tipo_ficheiro: "imagem",
        url_preview: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&w=800&q=80",
        destinatario: "maria.santos@email.com",
        observacoes_juridicas: "Confissão extrajudicial por escrito.",
        arquivado_no_arquivo_digital: true
      }
    ],
    historico_tramitacao: [
      {
        id_fase: "fase-201",
        data_hora: "2026-07-01 09:30",
        fase: "Deteção e Relatório Técnico",
        descricao: "Vistoria técnica regista o início de fecho não autorizado de varanda.",
        responsavel: "Equipa de Vistorias Técnicas"
      },
      {
        id_fase: "fase-202",
        data_hora: "2026-07-08 11:00",
        fase: "Envio de Notificação de Embargo AR",
        descricao: "Carta registada expedida pelos CTT a exigir suspensão e reposição.",
        responsavel: "Carlos Administrador"
      }
    ]
  }
];

